---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keptn-observability-config
  namespace: keptn-system
data:
  values.yaml: |
    lifecycleOperator:
      enabled: true
      env:
        otelCollectorUrl: jaeger-collector.jaeger.svc.cluster.local:4317
      
    metricsOperator:
      enabled: true
      env:
        exposeKeptnMetrics: "true"
