---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keptn-config
  namespace: keptn-system
spec:
  interval: 5m0s
  retryInterval: 1m0s
  timeout: 2m0s
  path: ./flux/config
  prune: true
  wait: true
  serviceAccountName: keptn-system
  targetNamespace: keptn-system
  dependsOn:
    - name: keptn-deploy
      namespace: keptn-system
  sourceRef:
    kind: GitRepository
    name: keptn-deploy
