---
apiVersion: options.keptn.sh/v1alpha1
kind: KeptnConfig
metadata:
  name: keptnconfig
  namespace: keptn-system
spec:
  OTelCollectorUrl: 'jaeger-collector.jaeger.svc.cluster.local:4317'
  keptnAppCreationRequestTimeoutSeconds: 30
  observabilityTimeout: 5m
