apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- keptn-alert.yaml
- keptn-helmrelease.yaml
- keptn-gitrepository.yaml
- keptn-observability-configmap.yaml
- slack-provider.yaml
- slack-notif-alert.yaml

