apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- keptn-alert.yaml
- keptn-helmrelease.yaml
- keptn-gitrepository.yaml
# KeptnConfig will be added after Keptn is deployed
# - keptn-config.yaml
- keptn-observability-configmap.yaml
- keptn-servicemonitor.yaml
- grafana-datasources.yaml
- grafana-dashboard-keptn-overview.yaml
- grafana-dashboard-keptn-applications.yaml
- grafana-dashboard-keptn-workloads.yaml
- slack-provider.yaml
- slack-notif-alert.yaml

