---
# ServiceAccount for subscriber-loader Keptn task
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subscriber-loader
  namespace: keptn-system
---
# ClusterRole for subscriber-loader to access Jobs and Pods
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscriber-loader
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
# ClusterRoleBinding for subscriber-loader
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subscriber-loader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: subscriber-loader
subjects:
  - kind: ServiceAccount
    name: subscriber-loader
    namespace: keptn-system
