---
# Workaround for Keptn 0.10.0 not honoring serviceAccountName in KeptnTaskDefinition
# Grant permissions to default SA in k8s-open5gs namespace since that's what gets used
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subscriber-loader-default-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: subscriber-loader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: k8s-open5gs
