annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/keptn/lifecycle-toolkit/issues/new
    - name: community
      url: https://slack.keptn.sh/
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Full Lifecycle
apiVersion: v2
appVersion: v2.5.0
dependencies:
- alias: certManager
  condition: global.certManagerEnabled
  name: keptn-cert-manager
  repository: https://charts.lifecycle.keptn.sh
  version: 0.3.0
- alias: lifecycleOperator
  condition: lifecycleOperator.enabled
  name: keptn-lifecycle-operator
  repository: https://charts.lifecycle.keptn.sh
  version: 0.6.0
- alias: metricsOperator
  condition: metricsOperator.enabled
  name: keptn-metrics-operator
  repository: https://charts.lifecycle.keptn.sh
  version: 0.5.0
description: A Helm chart for Keptn, a set of tools to enable cloud-native application
  lifecycle management
home: https://keptn.sh
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/keptn/icon/color/keptn-icon-color.svg
keywords:
- cloud-native
- lifecycle
- lifecycle-management
- application-lifecycle
- application-lifecycle-management
- orchestration
- keptn
- operator
- pre-deployment
- post-deployment
- metrics
- analysis
- evaluation
- certificate
kubeVersion: '>= 1.27.0-0'
name: keptn
sources:
- https://github.com/keptn/lifecycle-toolkit
type: application
version: 0.11.1
